###중복확인
POST http://localhost:8080/auth/idCheck
Content-Type: application/json

{
  "userId": "wepungsan5849"
}

###중복확인
POST http://localhost:8080/auth/nicknameCheck
Content-Type: application/json

{
  "nickname": "Cmung"
}



###회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "userId": "wepungsan5849",
  "nickname" : "cmung",
  "password": "Asd1234!",
  "passwordCheck": "Asd1234!"
}

###로그인
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "userId": "wepungsan5849",
  "password": "Asd1234!"
}